environment:
  matrix:
    - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python26-x64"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python32"
    - PYTHON: "C:\\Python32-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

build: off

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - git --version
    - python --version
    - pip --version
    - pip install --user --upgrade wheel setuptools

test_script:
    - python setup.py build
    - python setup.py test

after_test:
    - python setup.py bdist_wheel
    - python setup.py bdist_wininst
    # https://bugs.python.org/issue34251
    #- python setup.py bdist_msi
    - ps: ls dist

artifacts:
    - path: dist\*
